### ISSUE TITLE
[Issue] Slotlist in channel does not update

### ISSUE THREAD

**Issue by ancinape** [Katalam/slotlist-discord-bot#1]
**Describe the bug**
When a user takes a slot or removes a slot, the bot does not edit the slotlist message on Discord. However, when I retrieve the slotlist through a command, it displays the updated list

**To Reproduce**
1. !slot 1
2. 1-mission channel does not update with the new slot
3. !missioninfo 1
4. Outputs proper slotlist with the new slot

When I look at the console, I see the following error:
![image](https://user-images.githubusercontent.com/52501309/71125572-37f7b800-21b5-11ea-879a-369f33766dbe.png)

Also to mention, I am using Python 3.7 and the bot does have admin perms.

**Comment by Katalam** [comment]
Usage of slot command is `!slot 1 1` with first being the mission id and second the slot id for the mission

**Comment by ancinape** [comment]
Forgive the mistake, I meant to type `!slot 1 1` in my original issue.

**Comment by Katalam** [comment]
Which OS do you use? And how do you added the mission?

**Comment by ancinape** [comment]
The bot runs off a Fedora machine.

The mission is added using the following command:

![image](https://user-images.githubusercontent.com/52501309/71127070-4dbaac80-21b8-11ea-9414-8f2696bfc55c.png)

**Comment by Katalam** [comment]
I just tried to reproduce, but I wasn't able to do it. Could you point out what you have done step by step again pls? The problem is either the discord.py command that could not receive the message from the api but my program code what cannot be receive the message from the channel.

**Comment by ancinape** [comment]
I'll do a fresh reinstall and try again.
Here are the steps that I follow:

1. Enter project root directory through my bash terminal
2. `source bin/activate` to enter the python environment
The following packages are confirmed to be installed on the environment
- discord.py
- pyperclip
- python-dotenv
- sqlite3
3. `sqlite3 slotlist.db` to create the database
4. Copy and pasted `CREATE TABLE missions (mission_id INTEGER PRIMARY KEY, mission_name TEXT NOT NULL);` to set up the database
5. `.quit` to exit the database
6. `nano slots.txt` to edit the slots file. I do not have the ability to view any GUI on the server so I input the slots manually. It looks like the following:
![image](https://user-images.githubusercontent.com/52501309/71137565-abf68800-21d6-11ea-9f99-ace83b3540fe.png)
7. Exit nano and save the file
8. `python3 bot.py` to start the bot
9. I return to discord where I output the commands to a public channel. The following steps are on discord.

10. ![image](https://user-images.githubusercontent.com/52501309/71137763-3a6b0980-21d7-11ea-9416-ac844b443dc1.png)

11. ![image](https://user-images.githubusercontent.com/52501309/71137843-77370080-21d7-11ea-8299-b609e5a5d648.png)

12. ![image](https://user-images.githubusercontent.com/52501309/71137859-8322c280-21d7-11ea-9e4e-26cb3380f843.png)

13. I move the Missions category up several categories.

14. ![image](https://user-images.githubusercontent.com/52501309/71137913-ba916f00-21d7-11ea-9cdc-bc866244e7a9.png)

When I do this command, the terminal outputs the following again:

![image](https://user-images.githubusercontent.com/52501309/71137946-d563e380-21d7-11ea-9d23-6fce22d7f8f3.png)

Looking at the 1-operations-black-bear again, nothing has changed.

15. However, when I do the following, it shows me the proper slotlist:
![image](https://user-images.githubusercontent.com/52501309/71138007-0ba16300-21d8-11ea-83fb-e5ea1bd684e1.png)


I hope this helps understand the issue.

**Comment by Katalam** [comment]
Was was detailed,
quick question maybe the problem is there but I don’t think so. The slots in the `.txt` the last character should be a line break, try that pls.

**Comment by Katalam** [comment]
Ah no, i found the problem. Kinda obvious one. Your bot is not named `Slotlist`. You can replace the name of your bot here: https://github.com/Katalam/slotlist-discord-bot/blob/fefcb1f974ddc2f184f05626f5f02a4c327772af/bot.py#L227
That should fix the problem.

**Comment by ancinape** [comment]
Thank you, Katalam. That indeed was the issue. I have fixed the issue by replacing line 227 with the following:

`m = await ctx.history().get(author__id = bot.user.id)`

By using IDs, one could the awkward situation where an ill-informed user names themselves "Slotlist." This also works when the bot is under any name other than "Slotlist."

It could be a worthwhile replacement for your repository as well. I'd open a pull request but I feel this is far too small of a change. If you wish, you could commit this change to your repository.

You may also close this issue. As of now, everything works smoothly :)

**Comment by Katalam** [comment]
I replaced it in f652b2d748067f63fdd07872b49b1f408b605842 and thanks for the info
